# Site settings
title: <%= title %>
description: <%= description %>
gh_page: <%= gh_page %>
contact: george.lele.sun@gmail.com

# Front page settings
username: George Sun
header: <%= header %>
site_title: <% title %>
background_image: aaa

# Google-analytics
google-analytics:
  id: "UA-155355374-2"

exclude: ['package.json', 'src' , 'node_modules']
